apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo
    image: stress                  #压测镜像
    args:
    - --vm
    - "1"
    - --vm-bytes
    - 200M                       #需要200M
    resources:
      requests:
        memory: 50Mi               #资源至少要求50M
      limits: 
        memory: 100Mi              #资源最多被限制100M
