apiVersion: v1
kind: Service
metadata:
 name: nginx-svc         #svc名称
 labels:
  app: nginx
spec:
 ports:
 - port: 80
   name: web
 clusterIP: None            #定义无头服务
 selector:
  app: nginx               #选择器，匹配标签为app=nginx
