apiVersion: v1
kind: Service
metadata:
  name: ex-service
spec:
  type:  ExternalName
  externalName: test.jdcloud.com

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: demo
spec:
  type:  ExternalName
  externalName: ex-service.default.svc.cluster.local
