apiVersion: v1
kind: Service
metadata:
  name: lb-myapp
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
      app: myapp
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-myapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nyapp
        image: harbor.example.local/test/myapp:v2
        imagePullPolicy: IfNotPresent    #镜像拉取策略
