apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: harbor.example.local/library/nginx:latest
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /hostpath
      type: DirectoryOrCreate
  nodeName: node2
