apiVersion: v1
kind: Pod
metadata:
  name: nfs-pd
spec:
  containers:
  - image: harbor.example.local/library/nginx:latest
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nfs-volume
  volumes:
  - name: nfs-volume
    nfs:
      server: 192.168.0.11
      path: /nfs
