apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: myapp
    image: nginx:latest     #镜像版本
    imagePullPolicy: IfNotPresent    #镜像拉取策略
    ports:        #pod端口映射
    - name: http
      containerPort: 80
      hostPort: 80
    resources:        #pod资源限制
      limits:
        cpu: 1
        memory: 200Mi
      requests:
        cpu: 0.5
        memory: 100Mi

  - name: busyboxplus    #第二个容器
    image: harbor.example.local/test/busyboxplus:latest 
    imagePullPolicy: IfNotPresent    #镜像拉取策略
    stdin: True            #允许交互
    tty: True              #分配终端

  #nodeSelector:     #调度节点设置(只要符合相应标签的节点即可)
  #  kubernetes.io/hostname: node2
  hostNetwork: True    #是否使用宿主机网络
