apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-example
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent    #镜像拉取策略
#      nodeSelector:     #调度节点设置(只要符合相应标签的节点即可)
#        kubernetes.io/hostname: node3
